### ISSUE TITLE
doc previewer does not update module or function description when multiple modules

### ISSUE THREAD

**Issue by techieshark** [elm/elm-lang.org#610]
I've uploaded a `documentation.json` file to the [doc previewer](http://package.elm-lang.org/help/docs-preview), but the documentation shown is only accurate for the first (alphabetically) module in the .json file.

An example `documentation.json` file is here: https://gist.github.com/techieshark/0a51d135f755744299ff04bfdf17cf04

Output produced by the previewer looks like this for the example `Data` module: 

![image](https://cloud.githubusercontent.com/assets/1072292/16865601/528641d2-4aa9-11e6-895c-fe7ea702a1e7.png)

Which is correct, but when we look at `View` we see that the module and function comments haven't updated:

![image](https://cloud.githubusercontent.com/assets/1072292/16865634/84ed1aa6-4aa9-11e6-948f-261122100065.png)

If you look at the example .json, you'll see that the `View` module comment should be "View module provides main app view." and the `view` function comment should be "Example view function."

I've tested this on recent Chrome, Firefox, and Safari browsers.

**Comment by shuhei** [comment]
It's caused by https://github.com/elm-lang/package.elm-lang.org/issues/182

**Comment by evancz** [comment]
The doc preview feature was dropped from the package website with 0.19.0 because I wasn't the primary author and was unable to maintain it particularly well.

The plan is to bring something like this back in `elm reactor` someday. That way folks can preview their docs without even needing an internet connection. In the meantime, I believe https://github.com/dmy/elm-doc-preview is what folks are using these days for this!
